# Generated by Django 2.1.1 on 2018-09-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=200)),
                ('node_mac', models.CharField(max_length=200)),
                ('gateway_id', models.CharField(max_length=200)),
                ('client_ip', models.CharField(max_length=200)),
                ('client_mac', models.CharField(max_length=200)),
                ('logged_in', models.DateTimeField()),
            ],
        ),
    ]
