# Generated by Django 2.1.1 on 2018-09-07 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
